"""One-page PDF executive summary export."""

from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.utils.app_timezone import filename_timestamp


def build_executive_pdf(
    *,
    company_name: str,
    metrics: dict,
    analysis_id: str | None = None,
) -> tuple[bytes, str]:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("CommerceFlow — Executive Summary", styles["Title"]))
    story.append(Paragraph(company_name or "Workspace", styles["Heading2"]))
    if analysis_id:
        story.append(Paragraph(f"Analysis ID: {analysis_id}", styles["Normal"]))
    story.append(Spacer(1, 0.2 * inch))

    rows = [["Metric", "Value"]]
    labels = {
        "total_revenue": "Total Revenue",
        "gross_margin_pct": "Gross Margin %",
        "inventory_efficiency": "Inventory Efficiency",
        "operational_risk_score": "Operational Risk",
        "profit_leakage_estimate": "Profit Leakage",
        "dead_inventory_value": "Dead Inventory",
        "product_count": "Active Products",
        "avg_order_value": "Avg Order Value",
    }
    for key, label in labels.items():
        value = metrics.get(key)
        if value is None:
            display = "N/A"
        elif key.endswith("_pct"):
            display = f"{float(value):.1f}%"
        elif isinstance(value, (int, float)):
            display = f"{value:,.2f}" if isinstance(value, float) else f"{value:,}"
        else:
            display = str(value)
        rows.append([label, display])

    table = Table(rows, colWidths=[3.2 * inch, 2.5 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 0.3 * inch))
    story.append(
        Paragraph(
            "Generated by CommerceFlow. Run Your Analysis before exporting for live KPIs.",
            styles["Italic"],
        )
    )

    doc.build(story)
    ts = filename_timestamp()
    return buffer.getvalue(), f"commerceflow_executive_{ts}.pdf"
